# .github/workflows/docker-build.yml
name: CI/CD Docker Build and Push

# Syarat 9: Proses CI/CD untuk build image dari repo Git
on:
  push:
    branches: [ "main" ] # Jalankan workflow setiap ada push ke branch main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/uas-asj-percobaan1:latest